Task_1_2_2
kapkekes/nsu-object-oriented-programming pull request #10
Opened 2022-10-10 13:40 UTC by kapkekes

Ещё в процессе, открываю PR на софт-дедлайн.

2022-10-12 13:06 UTC, alradish requested changes
- Тесты

2022-10-12 13:06 UTC, alradish commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +    private static class TreeIterator<T> implements Iterator<T> {
Лучше перенести его в самый конец класса

2022-10-12 13:06 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +        private TreeIterator(List<Tree<T>> traversed) {
Итерироваться через всё дерево ещё даже до создания итератора не очень хорошая идея. Нужно, чтобы это делал итератор, и только столько, сколько нужно.

2022-10-12 13:06 UTC, alradish commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +            descendants.addAll(descendant.depthFirst());
Перепишите итеративно

2022-10-12 13:06 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +    public Tree(E val) throws NullPointerException {
Класс лучше начинать с объявления полей, потом конструкторы, потом методы и в конце иннер классы

2022-10-12 13:06 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +            throw new ConcurrentModificationException(
Исключение должен бросать итератор

2022-10-12 14:59 UTC, kapkekes commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +            throw new ConcurrentModificationException(
@Leidenn2509, итератор должен бросать исключение сразу же, когда пытаются сделать недопустимое действие? Или итератор, к примеру, может на вызове `next()` проверять, было ли сделано что-то незаконное, и в случае чего выкидывать `ConcurrentModificationException`?

2022-10-13 07:16 UTC, kapkekes commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +    public Tree(E val) throws NullPointerException {
Принял, переместил всё на свои места.

2022-10-17 14:57 UTC, kapkekes commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +    private static class TreeIterator<T> implements Iterator<T> {
Перенёс.

2022-10-17 14:57 UTC, kapkekes commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +            descendants.addAll(descendant.depthFirst());
Переписал.

2022-10-17 14:57 UTC, kapkekes commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +        private TreeIterator(List<Tree<T>> traversed) {
Сделал.

2022-10-17 14:58 UTC, kapkekes commented on Task_1_2_2/src/main/java/io/github/kapkekes/Tree.java
> +            throw new ConcurrentModificationException(
Реализовал выброс из итератора.

2022-10-18 10:12 UTC, Leidenn2509 approved these changes

2022-10-18 10:12 UTC, merged