Task_1_3_1
kapkekes/nsu-object-oriented-programming pull request #12
Opened 2022-11-09 10:06 UTC by kapkekes

Пока что открываю на soft deadline, но, может, до конца дня допишу полностью.

2022-11-11 08:36 UTC, alradish requested changes

2022-11-11 08:36 UTC, alradish commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +        int index;
Вроде можно перенести в цикл

2022-11-11 08:36 UTC, alradish commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +        List<Integer> z = IntStream.of(0).boxed().collect(Collectors.toList());
Выглядит страшно. Кажется можно просто создать лист и установить первый элемент в 0

2022-11-11 08:36 UTC, alradish commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +        List<Integer> z = IntStream.of(0).boxed().collect(Collectors.toList());
\+ тут непонятно какой лист вам вернулся. Хотелось бы иметь ArrayList чтобы быть более эффективным. Можно даже сразу создать лист нужного размера. Или ещё лучше просто создать массив
```Java
int[] z = new int[string.length];
```

2022-11-11 08:36 UTC, alradish commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +    public static Optional<Integer> substringIndex(String pattern, BufferedReader text) {
Чтобы обобщить эту функцию принимайте InputStream/Reader и оборачивайте их в BufferedReader

2022-11-12 12:09 UTC, kapkekes commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +        List<Integer> z = IntStream.of(0).boxed().collect(Collectors.toList());
Возвращать массив примитивов - это нормальная практика?

2022-11-13 10:20 UTC, kapkekes commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +        int index;
Если вы про определение `index`, то перенёс.

2022-11-13 10:55 UTC, kapkekes commented on Task_1_3_1/src/main/java/io/github/kapkekes/StringUtilities.java
> +    public static Optional<Integer> substringIndex(String pattern, BufferedReader text) {
То есть, нужно сделать что-то вроде:
```java
    public static Optional<Integer> substringIndex(String pattern, Reader text) {
        BufferedReader bufferedText = new BufferedReader(text);
        ...
    }
```
И работать уже с `bufferedText`, а не с `text`?

2023-04-02 09:19 UTC, closed without merging