Task_1_4_1
kapkekes/nsu-object-oriented-programming pull request #13
Opened 2022-11-23 14:35 UTC by kapkekes

Открыл на soft deadline, сейчас читаю, как писать на Kotlin'е.

2022-12-06 12:30 UTC, alradish requested changes
Котлин класс

2022-12-19 17:27 UTC, kapkekes commented
Пойду настраивать workflow под `[dokka](https://github.com/Kotlin/dokka)`, но это уже совсем другая история...

2022-12-19 19:59 UTC, kapkekes commented
> Пойду настраивать workflow под [`dokka`](https://github.com/Kotlin/dokka), но это уже совсем другая история...

Окей, ценой нервов и часа времени оно завелось. Теперь workflow будет генерировать javadoc'и для Java-кода и kdoc'и с помощью Dokka для Kotlin-кода.

2022-12-19 20:02 UTC, kapkekes commented
вот би били плюсики за создание environment'а...

2022-12-20 10:32 UTC, kapkekes commented
Теперь и **KDoc** через `Dokka` генерируется, и код проверяется через `Ktlint`. Можно спокойно жить на Koltin'е.

2022-12-21 05:09 UTC, kapkekes commented
Бот как-то очень странно оценивает coverage в классе Person, там, на самом деле, проверять нечего.
Это data class по определению.

2022-12-23 11:27 UTC, alradish approved these changes

2022-12-23 11:27 UTC, merged