Task_1_5_1
kapkekes/nsu-object-oriented-programming pull request #14
Opened 2022-12-13 11:27 UTC by kapkekes

Просто открываю PR, на софт-дедлайн все равно не успел, но хотя бы на dead закрою.

2022-12-19 02:44 UTC, alradish requested changes
Я мягкий сдвинул, так что успели

2022-12-19 02:44 UTC, alradish commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val isReal: Boolean by lazy { imaginary == 0.0 }
А зачем лениво? Я уверен посчитать равенство не сильно затратная операция

2022-12-19 02:44 UTC, alradish commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val abs: Double by lazy { sqrt(real * real + imaginary * imaginary) }
same ^

2022-12-19 03:13 UTC, kapkekes commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val isReal: Boolean by lazy { imaginary == 0.0 }
А у меня все операции как бы на комплексных числах. Если считать не лениво, то количество операций возрастёт в квадрат.

2022-12-28 06:21 UTC, kapkekes commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val abs: Double by lazy { sqrt(real * real + imaginary * imaginary) }
Только сейчас понял, что 12-я строчка, потенциально, вообще может компилятор в неудобное положение поставить, если бы это было бы не ленивое свойство.
Создаётся новый `Complex`, для него считается `conjugate`, то есть создаётся новый `Complex` - и всё, цикл замкнулся.

2022-12-28 15:01 UTC, alradish commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val isReal: Boolean by lazy { imaginary == 0.0 }
Преждевременная оптимизация. Я на 100% уверен всё будет нормально

2022-12-28 15:02 UTC, alradish commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val abs: Double by lazy { sqrt(real * real + imaginary * imaginary) }
Потому, что это должен быть метод (ну либо `get() = Complex(real, -imaginary)`)

2022-12-28 15:02 UTC, kapkekes commented on Task_1_5_1/src/main/kotlin/io/github/kapkekes/Complex.kt
> +    val abs: Double by lazy { sqrt(real * real + imaginary * imaginary) }
Не уходите, минутку.

2022-12-28 15:03 UTC, alradish approved these changes

2022-12-28 15:03 UTC, merged