Task 1.1.1
kapkekes/nsu-object-oriented-programming pull request #3
Opened 2022-09-13 12:41 UTC by kapkekes

Javadoc'и допишу в ближайшее время.

2022-09-13 12:46 UTC, Leidenn2509 requested changes
- Удалите `.idea` из корня репозитория
- Исправьте все замечания по стилю
- Не забудьте добавить скрипт сборки

2022-09-13 12:46 UTC, Leidenn2509 commented on Task-1.1.1/src/main/java/io/github/kapkekes/sortings/Heap.java
> +public class Heap {
Всё же лучше `Heapsort` ну или что-то с `sort`. Название `Heap` звучит как структура данных

2022-09-13 12:46 UTC, Leidenn2509 commented on Task-1.1.1/src/test/java/io/github/kapkekes/sortings/HeapTest.java
> +    void simpleTest() {
Модификаторы доступа обязательны

2022-09-15 05:30 UTC, kapkekes commented on Task-1.1.1/src/main/java/io/github/kapkekes/sortings/Heap.java
> +public class Heap {
Изменил имя пакета на `io.github.kapkekes` и имя класса на `HeapSort`.

2022-09-15 05:30 UTC, kapkekes commented on Task-1.1.1/src/test/java/io/github/kapkekes/sortings/HeapTest.java
> +    void simpleTest() {
Добавил модификаторы доступа.

2022-09-15 06:37 UTC, Leidenn2509 requested changes
- Исправьте название PR, должно быть `Task_1_1_1`
- Исправьте название проекта и папки, должно быть `Task_1_1_1`

2022-09-15 06:37 UTC, Leidenn2509 commented on Task-1.1.1/src/main/java/io/github/kapkekes/HeapSort.java
> +    private static <E extends Comparable<E>> void heapTransform(E[] array, int size, int index) {
Приватные методы разрешается не документировать

2022-09-15 06:39 UTC, kapkekes commented on Task-1.1.1/src/main/java/io/github/kapkekes/HeapSort.java
> +    private static <E extends Comparable<E>> void heapTransform(E[] array, int size, int index) {
Разрешается, но почему бы и нет.

2022-09-15 07:55 UTC, closed without merging