Task_1_2_1
kapkekes/nsu-object-oriented-programming pull request #9
Opened 2022-09-15 08:28 UTC by kapkekes

Изменил названия модуля, ветки и PR.

2022-09-21 10:16 UTC, Leidenn2509 requested changes

2022-09-21 10:16 UTC, alradish commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +    protected static final int minimalLength = 2;
Имя константы должно следовать код стайлу https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2022-09-21 10:16 UTC, alradish commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +    protected Object[] array;
Я бы советовал здесь использовать `private`, так как никакого наследования нет и не подразумевается

2022-09-21 10:16 UTC, alradish commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +            this.resizeStack(this.used << 1);
Сдвиг тут точно не нужен и даже вреден. https://stackoverflow.com/questions/4072703/should-i-bit-shift-to-divide-by-2-in-java
В основном важен пункт
`You're not going to outsmart a compiler for optimization on something that simple so don't bother trying`
Ну и в принципе это немного путает при чтении кода. Ощущение, что здесь происходит что-то страшное, что пришлось оптимизировать, хотя это не так

2022-09-21 10:16 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +        Optional<E> element = (Optional<E>) Optional.of(this.array[--this.used]);
Лучше внести каст внутрь, т.е. кастовать элемент массива к `E`

2022-09-21 12:12 UTC, kapkekes commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +    protected Object[] array;
Можно использовать `package-private`? Мне необходим доступ к параметрам стека для надлежащего тестирования, однако выдавать эти параметры пользователю - это просто засорить пространство символов.

2022-09-21 12:13 UTC, kapkekes commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +            this.resizeStack(this.used << 1);
Принял к сведению, с **C** bit-shift тянется.

2022-09-21 12:14 UTC, kapkekes commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +        Optional<E> element = (Optional<E>) Optional.of(this.array[--this.used]);
Справедливо, не подумал даже.

2022-09-21 12:23 UTC, kapkekes commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +    protected static final int minimalLength = 2;
Забыл, исправил.

2022-09-21 12:57 UTC, kapkekes commented on Task_1_2_1/src/main/java/io/github/kapkekes/Stack.java
> +    protected Object[] array;
Исправил.

2022-09-23 09:50 UTC, Leidenn2509 approved these changes

2022-09-23 09:50 UTC, merged